### ISSUE TITLE
Resolution issues

### ISSUE THREAD

**Issue by ghost** [TomONeill/persistentdesktopicons#2]
Crashes when launching after resolution changing. Also there are some very poor screens with resolution bug, which can cause this after you waked notebook from hibernation.
Yes, it crashes after hibernation

**Comment by TomONeill** [comment]
Can you share the log file?

I don't understand this line:
`Also there are some very poor screens with resolution bug, which can cause this after you waked notebook from hibernation.`

**Comment by TomONeill** [comment]
I am closing this one due to inactivity.
